# Generated by Django 5.1.1 on 2026-06-09 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_address', models.CharField(max_length=255)),
                ('total_tables', models.IntegerField()),
                ('total_employees', models.IntegerField()),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
