# Generated by Django 5.1.1 on 2026-06-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hotelsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.hotelsettings'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
